services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    IntelligentIntern\LokiBundle\Service\:
        resource: '../src/Service/*'
        public: true
        tags:
            - { name: 'log.strategy' }
