services:
    IntelligentIntern\LokiBundle\Service\:
        resource: '../src/Service/*'
        public: true
        tags:
            - { name: 'log.strategy' }

    App\Factory\LogServiceFactory:
        arguments:
            $vaultService: '@App\Service\VaultService'
            $logResolver: '@App\Domain\LogResolver'
        public: true